services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mysql-network
    
networks:
  mysql-network:
    driver: bridge
